# -*- coding: utf-8 -*-
"""LabyTechInf21.03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GAIASxEVYWt7VutKZkVo_Zm5CLP8T8C-
"""

import math as m
import time


# Filip Gajewski 251687 zadanie 4
# poniższa lista opisów dotyczy opisów zadań do wykonania, taka forma ułatwia modyfikowanie opisów zadań
description = [
    "Program pobiera dwa stringi oraz wyświetla ich długość i je modyfikuje.",
    "Program zmienia w stringu literkę na znak oraz zmienia na litery małe i duże.",
    "Program wyświetla wszystkie litery ze stringu na dwa sposoby.",
    "Program wyświetla alfabet jako string oraz wyśwoetla jego wycinki.",
    "Program sprawdza czy string zawiera wyraz oraz modyfikuje string za tym wyrazem."
]


# funkcja która pobiera od użytkownika liczbę i nie pozwala wczytać innej wartości
# dla poprawnego działania powinno się ją używać w następujący sposób:
# user_input = get_num_input("Enter the number: ")
def get_num_input(prompt):
    while True:
        try:
            user_num_input = int(input(prompt))
            return user_num_input
        except ValueError:
            print("Podana wartość nie jest liczbą. Spróbuj ponownie.")


def ex1():
    print("\n---ZADANIE PIERWSZE---\n")
    str1 = input("Podaj pierwszy string: ")
    str2 = input("Podaj drugi string: ")
    print(f'Pierwszy string: "{str1}" oraz drugi: "{str2}".')
    print(f'Długość pierwszego stringu: {len(str1)}')
    print(f'Długość drugiego stringu: {len(str2)}')
    print(f'Konkatenacja tych stringów ze spacją: {str1 + " " + str2}')
    print(f'Nowy string: {2 * str1 + str2}')


def ex2():
    print("\n---ZADANIE DRUGIE---\n")
    str1 = input("Podaj krótkie zdanie jako string: ")
    letter = input("Podaj literke, która chcesz zastapic: ")
    sign = input("Podaj znak, którym chcesz zastapic literke: ")
    print(f'String z zamienionymi znakami "{letter}" na "{sign}": {str1.replace(letter, sign)}')
    print(f'String z zamienionymi wielkimi na małe litery: {str1.lower()}')
    print(f'String z zamienionymi małymi na wielkielitery: {str1.upper()}')


def ex3():
    print("\n---ZADANIE TRZECIE---\n")
    str1 = input("Podaj krótkie zdanie jako string: ")

    print('\Pierwszy sposób:\n')
    for i in range(len(str1)):
      print(str1[i], end=' ')

    print('\nDrugim sposobem:\n')
    for letter in str1:
      print(letter, end=' ')

    print("")


def ex4():
    print("\n---ZADANIE CZWARTE---\n")
    str1 = ""
    for i in range(ord('a'), ord('z') + 1):
      str1 += chr(i)
    print(f'Wycięty string od znaków {3} do {7}: {str1[2:7]}')
    print(f'Wycięty string z pierwszych {10} znaków: {str1[:10]}')
    print(f'Wycięty string po 15-tym znaku: {str1[15:]}')


def ex5():
    print("\n---ZADANIE PIĄTE---\n")
    str1 = 'Organizatorom marszu plany pokrzyżowała pogoda, która pogorszyła się w ciągu kwadransa'
    if str1.find('pogoda') == -1:
      print('Ten string nie zawiera wyrazu "pogoda".')
    else:
      print('Ten string zawiera wyraz "pogoda".')
      index = str1.index('pogoda')
      print(str1[:index] + str1[(index + len('pogoda')):].upper())


# główna funkcja, która zarządza działaniem programu jeżeli jest on poprawnie uruchomiony (nie importowany jako moduł)
if __name__ == '__main__':
    print("\nWitam w moim programie na Technologie Informatyczne 4.")
    print("Program ma na celu wykonywanie zadań z dokumentacji.")
    print("W celu realizacji danego zadania podaj jego numer, a w celu zakończenia programu wpisz numer zadania 0.")
    time.sleep(1)
    for i in range(0, len(description)):
        print(f"{chr(0x2022)} Zadanie {i + 1}.\n Opis: {description[i]}")
        time.sleep(0.5)

    while True:
        try:
            user_choice = int(get_num_input("\nPodaj numer zadania, które chcesz wykonać: "))
            if user_choice == 0:
                break
            elif user_choice == 1:
                ex1()
            elif user_choice == 2:
                ex2()
            elif user_choice == 3:
                ex3()
            elif user_choice == 4:
                ex4()
            elif user_choice == 5:
                ex5()
            else:
                print("Nieznany numer funkcji, podaj poprawny numer od 1 do 5.")
        except:
            print("Błedny numer zadania, podaj poprawna liczbe!")

    print("\nDziękuję za skorzystanie z mojego programu.")
    input()